### ISSUE TITLE
How to insert new line within body?

### ISSUE THREAD

**Issue by winseyli** [ErickMaeda/react-native-email-action#2]
Nice library. Thank you.

**Comment by ErickMaeda** [comment]
Hi @winseyli, thanks!

So, actually you can use `\n` to break line. However, in **iOS** **Gmail** there's a known issue that is not possible to send in this way. If you really need this to work for now, you'll need to implement a native solution for iOS. You can also take a look here https://stackoverflow.com/a/44448540/5161609 
But for other apps and platforms should work fine!

ex. 
```javascript
{
   ...options
   body "1st line.\n 2nd line.\n 3rd line.\n 4th line."
};
```
